var React = React || {};
React.Component = React.Component || null;
React.createContext = React.createContext || function() {};
var ReactDOM = ReactDOM || {};
var Fabric = Fabric || {};
Fabric.TextField = Fabric.TextField || {};
React.PureComponent = React.PureComponent || null;
var PropTypes = PropTypes || {};
PropTypes.func = PropTypes.func || {};
